import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';

import {
  ButtonModule,
  SplitButtonModule
} from 'primeng/primeng';

import {
  CindyButton,
  CindySplitButton,
  CindyBar,
  CindyDoughnut,
  CindyLine,
  CindyPie,
  CindyPolarArea,
  CindyRadar,
  CindyCarousel,
  CindyDataGrid,
  CindyDataList,
  CindyDataScroller,
  CindyGMap,
  CindyOrderList,
  CindyOrgChart,
  CindyPaginator,
  CindyPickList,
  CindySchedule,
  CindyTree,
  CindyTreeTable,
  CindyDragDrop,
  CindyUpload,
  CindyAutoComplete,
  CindyCalendar,
  CindyCheckbox,
  CindyChips,
  CindyColorPicker,
  CindyDropdown,
  CindyEditor,
  CindyInputGroup,
  CindyInputSwitch,
  CindyInputText,
  CindyInputTextArea,
  CindyListBox,
  CindyMask,
  CindyMultiSelect,
  CindyPassword,
  CindyRadioButton,
  CindyRating,
  CindySlider,
  CindySpinner,
  CindyToggleButton,
  CindyTriCheckbox,
  CindyBreadcrumb,
  CindyContextMenu,
  CindyMegaMenu,
  CindyMenu,
  CindyMenubar,
  CindyPanelMenu,
  CindySlideMenu,
  CindySteps,
  CindyTabMenu,
  CindyTieredMenu,
  CindyGrowl,
  CindyMessages,
  CindyBlockUI,
  CindyCaptcha,
  CindyCodeHighlighter,
  CindyDefer,
  CindyInplace,
  CindyProgressBar,
  CindyResponsive,
  CindyRTL,
  CindyTerminal,
  CindyValidation,
  CindyGalleria,
  CindyConfirmDialog,
  CindyDialog,
  CindyLightbox,
  CindyOverlayPanel,
  CindyTooltip,
  CindyPageTop,
  CindyAccordion,
  CindyFieldset,
  CindyGrid,
  CindyPanel,
  CindyTabView,
  CindyToolbar,
} from './components';

import {
  CindyEmailValidator,
  CindyEqualPasswordsValidator,
} from './validators';


const CINDY_COMPONENTS = [
  CindyButton,
  CindySplitButton,
  CindyBar,
  CindyDoughnut,
  CindyLine,
  CindyPie,
  CindyPolarArea,
  CindyRadar,
  CindyCarousel,
  CindyDataGrid,
  CindyDataList,
  CindyDataScroller,
  CindyGMap,
  CindyOrderList,
  CindyOrgChart,
  CindyPaginator,
  CindyPickList,
  CindySchedule,
  CindyTree,
  CindyTreeTable,
  CindyDragDrop,
  CindyUpload,
  CindyAutoComplete,
  CindyCalendar,
  CindyCheckbox,
  CindyChips,
  CindyColorPicker,
  CindyDropdown,
  CindyEditor,
  CindyInputGroup,
  CindyInputSwitch,
  CindyInputText,
  CindyInputTextArea,
  CindyListBox,
  CindyMask,
  CindyMultiSelect,
  CindyPassword,
  CindyRadioButton,
  CindyRating,
  CindySlider,
  CindySpinner,
  CindyToggleButton,
  CindyTriCheckbox,
  CindyBreadcrumb,
  CindyContextMenu,
  CindyMegaMenu,
  CindyMenu,
  CindyMenubar,
  CindyPanelMenu,
  CindySlideMenu,
  CindySteps,
  CindyTabMenu,
  CindyTieredMenu,
  CindyGrowl,
  CindyMessages,
  CindyBlockUI,
  CindyCaptcha,
  CindyCodeHighlighter,
  CindyDefer,
  CindyInplace,
  CindyProgressBar,
  CindyResponsive,
  CindyRTL,
  CindyTerminal,
  CindyValidation,
  CindyGalleria,
  CindyConfirmDialog,
  CindyDialog,
  CindyLightbox,
  CindyOverlayPanel,
  CindyTooltip,
  CindyPageTop,
  CindyAccordion,
  CindyFieldset,
  CindyGrid,
  CindyPanel,
  CindyTabView,
  CindyToolbar,
];

const NGA_VALIDATORS = [
  CindyEmailValidator,
  CindyEqualPasswordsValidator,
];


@NgModule({
  declarations: [
    ...CINDY_COMPONENTS,
  ],
  imports: [
    CommonModule,
    ReactiveFormsModule,
    ButtonModule,
    RouterModule,
    FormsModule,
    SplitButtonModule,
  ],
  exports: [
    ...CINDY_COMPONENTS,
    RouterModule
  ]
})
export class CindyModule {
  static forRoot(): ModuleWithProviders {
    return <ModuleWithProviders>{
      ngModule: CindyModule,
      providers: [
        ...NGA_VALIDATORS,
      ]
    };
  }
}